/* @flow */

import * as AntimutableArray from '../'
import test from 'tape'

test('test noop', test => {
  const array = [1, 2, 3, 4, 5]
  const blank = []

  test.equal(AntimutableArray.remove(0, 0, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.equal(AntimutableArray.remove(0, -1, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.equal(AntimutableArray.remove(0, -2, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.equal(AntimutableArray.remove(0, -22, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.equal(AntimutableArray.remove(5, 2, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.equal(AntimutableArray.remove(7, 3, array), array)
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.equal(AntimutableArray.remove(0, 1, blank), blank)
  test.deepEqual(blank, [])
  test.equal(AntimutableArray.remove(4, -1, blank), blank)
  test.deepEqual(blank, [])
  test.equal(AntimutableArray.remove(0, 0, blank), blank)
  test.deepEqual(blank, [])

  test.end()
})

test('test remove preceeding', test => {
  const array = [1, 2, 3, 4, 5]

  test.deepEqual(AntimutableArray.remove(0, -1, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, -2, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, -3, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, -4, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, -5, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, -12, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(1, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, -1, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, -2, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, -3, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, -4, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, -14, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(2, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -1, array), [1, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -2, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -3, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -4, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -5, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, -12, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(3, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -1, array), [1, 2, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -2, array), [1, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -3, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -4, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -5, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -6, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, -16, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(4, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -1, array), [1, 2, 3, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -2, array), [1, 2, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -3, array), [1, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -4, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -5, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -6, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -7, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, -77, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(5, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -1, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -2, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -3, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -4, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -5, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -6, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -7, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(5, -77, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(7, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -1, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -2, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -3, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -4, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -5, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -6, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -7, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -8, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -9, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(7, -77, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.end()
})

test('test remove following', test => {
  const array = [1, 2, 3, 4, 5]

  test.deepEqual(AntimutableArray.remove(0, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 1, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 2, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 3, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 4, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 5, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(0, 5, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(1, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 1, array), [1, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 2, array), [1, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 3, array), [1, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 4, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 5, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 6, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(1, 66, array), [1])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(2, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 1, array), [1, 2, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 2, array), [1, 2, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 3, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 4, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 5, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(2, 55, array), [1, 2])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(3, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, 1, array), [1, 2, 3, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, 2, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, 3, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, 4, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(3, 44, array), [1, 2, 3])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(4, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, 1, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, 2, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, 3, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(4, 33, array), [1, 2, 3, 4])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(-1, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 1, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 2, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 3, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 4, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 5, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 6, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 7, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-1, 77, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(-2, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 1, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 2, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 3, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 4, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 5, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 6, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 7, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 8, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-2, 88, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.deepEqual(AntimutableArray.remove(-7, 0, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 1, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 2, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 3, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 4, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 5, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 7, array), [1, 2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 8, array), [2, 3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 9, array), [3, 4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 10, array), [4, 5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 11, array), [5])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 12, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 13, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])
  test.deepEqual(AntimutableArray.remove(-7, 113, array), [])
  test.deepEqual(array, [1, 2, 3, 4, 5])

  test.end()
})
